<#import "layout.ftlh" as layout><@layout.emailLayout footer="Diese E-Mail wurde automatisch versendet, weil eine Änderung deiner E-Mail-Adresse bei Voenix Shop angefordert wurde.">
<tr><td style="padding:32px 32px 16px"><h2>E-Mail-Änderung angefordert</h2><p>Es wurde eine Änderung deiner E-Mail-Adresse zu <strong>${newEmail}</strong> angefordert. Wenn die neue Adresse bestätigt wird, wird diese E-Mail-Adresse nicht mehr mit deinem Konto verknüpft sein.</p></td></tr>
<tr><td style="padding:0 32px 24px"><p>Falls du diese Änderung nicht selbst angefordert hast, ändere bitte umgehend dein Passwort.</p></td></tr>
</@layout.emailLayout>
