modules:
  - app
  - modules/account
  - modules/country
  - modules/email
  - modules/image
  - modules/magic-coins
  - modules/platform
  - modules/pricing
  - modules/production
  - modules/supplier
  - modules/test-support
  - modules/vat
  - plugins/detekt
  - plugins/ktfmt
  - plugins/ktlint

plugins:
  - ./plugins/detekt
  - ./plugins/ktfmt
  - ./plugins/ktlint
