package shop.voenix.production.pdf

import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption

/**
 * Filesystem persistence of immutable production artifacts under a production-owned private root.
 *
 * Every artifact lives at `{root}/{jobId}/{fileName}` — the job id keeps two suppliers' PDFs for
 * the same order apart even though both carry the producer-facing name `ORD-{orderId}.pdf`. A write
 * goes to a temporary file in the final directory followed by an atomic rename, so a partially
 * written PDF is never visible under the final path; repeating a write after a crash simply
 * replaces the file atomically. [load] recomputes the SHA-256 digest and compares it against the
 * value recorded in the database, so a delivery can prove it ships exactly the generated bytes.
 */
internal class ProductionArtifactStore(root: Path) {
    private val root: Path = Files.createDirectories(root.toAbsolutePath().normalize()).toRealPath()

    fun write(jobId: Long, fileName: String, bytes: ByteArray): Path {
        val target = resolve(jobId, fileName)
        val directory = Files.createDirectories(target.parent)
        val temporary = Files.createTempFile(directory, "$fileName.", ".tmp")
        try {
            Files.write(temporary, bytes)
            Files.move(
                temporary,
                target,
                StandardCopyOption.ATOMIC_MOVE,
                StandardCopyOption.REPLACE_EXISTING,
            )
        } finally {
            Files.deleteIfExists(temporary)
        }
        return target
    }

    fun load(jobId: Long, fileName: String, expectedSha256: String): ProductionArtifactLoadResult {
        val target = resolve(jobId, fileName)
        if (!Files.isRegularFile(target)) return ProductionArtifactLoadResult.Missing
        val bytes = Files.readAllBytes(target)
        val actualSha256 = sha256Hex(bytes)
        return if (actualSha256.equals(expectedSha256, ignoreCase = true)) {
            ProductionArtifactLoadResult.Loaded(bytes)
        } else {
            ProductionArtifactLoadResult.DigestMismatch(actualSha256)
        }
    }

    private fun resolve(jobId: Long, fileName: String): Path {
        require(jobId > 0) { "Production artifacts require a positive job id" }
        val directory = root.resolve(jobId.toString())
        val target = directory.resolve(fileName).normalize()
        require(target.parent == directory && target.fileName.toString() == fileName) {
            "Production artifact file name must be a plain file name"
        }
        return target
    }
}
