package shop.voenix.production.delivery

import java.awt.Color
import java.nio.file.Files
import java.nio.file.Path
import java.security.MessageDigest
import java.time.LocalDate
import java.util.HexFormat
import javax.sql.DataSource
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import org.jetbrains.exposed.v1.jdbc.Database
import org.jetbrains.exposed.v1.jdbc.transactions.suspendTransaction
import shop.voenix.production.ProductionData
import shop.voenix.production.ProductionItem
import shop.voenix.production.ProductionSource
import shop.voenix.production.pdf.ProductionArtifactLoadResult
import shop.voenix.production.pdf.ProductionArtifactStore
import shop.voenix.production.pdf.ProductionPdfRenderer
import shop.voenix.production.pdf.newTempDirectory
import shop.voenix.production.pdf.writePng
import shop.voenix.testing.PostgresIntegrationTest

internal class ProductionArtifactGenerationIntegrationTest : PostgresIntegrationTest() {
    private val artifactRoot = newTempDirectory()
    private val imageDirectory = newTempDirectory()

    @AfterTest
    fun cleanUp() {
        artifactRoot.toFile().deleteRecursively()
        imageDirectory.toFile().deleteRecursively()
    }

    @Test
    fun `the artifact is generated exactly once and later scans skip the job`() = runBlocking {
        migratedDataSource("production-artifact-once-test").use { dataSource ->
            prepare(dataSource)
            val database = Database.connect(dataSource)
            val repository = ProductionRequestRepository(database)
            enqueue(database, repository, orderId = 10)
            val image = writePng(imageDirectory, "item.png")
            val worker = worker(database, repository) { orderId -> order(orderId, image) }

            worker.runOnce()

            val job = jobState(dataSource)
            assertEquals(1, job.attempts)
            assertNull(job.errorCode)
            assertNotNull(job.generatedAt)
            val sha256 = assertNotNull(job.contentSha256)
            val artifact = artifactRoot.resolve("${job.id}").resolve("ORD-10.pdf")
            val bytes = Files.readAllBytes(artifact)
            assertTrue(bytes.decodeToString(0, 5).startsWith("%PDF-"), "artifact is not a PDF")
            assertEquals(sha256, sha256Hex(bytes))
            assertEquals(
                listOf(artifact),
                Files.list(artifact.parent).use { entries -> entries.toList() },
            )

            worker.runOnce()

            val unchanged = jobState(dataSource)
            assertEquals(1, unchanged.attempts)
            assertEquals(sha256, unchanged.contentSha256)
            assertEquals(job.generatedAt, unchanged.generatedAt)
            assertContentEquals(bytes, Files.readAllBytes(artifact))
        }
    }

    @Test
    fun `changed master data and images never change the generated bytes`() = runBlocking {
        migratedDataSource("production-artifact-immutable-test").use { dataSource ->
            prepare(dataSource)
            val database = Database.connect(dataSource)
            val repository = ProductionRequestRepository(database)
            enqueue(database, repository, orderId = 20)
            var image = writePng(imageDirectory, "before.png", color = Color.RED)
            var articleName = "Zaubertasse"
            val worker =
                worker(database, repository) { orderId -> order(orderId, image, articleName) }

            worker.runOnce()
            val generated = jobState(dataSource)
            val artifact = artifactRoot.resolve("${generated.id}").resolve("ORD-20.pdf")
            val bytes = Files.readAllBytes(artifact)

            image = writePng(imageDirectory, "after.png", color = Color.BLUE)
            articleName = "Umbenannt"
            worker.runOnce()

            assertEquals(generated.contentSha256, jobState(dataSource).contentSha256)
            assertContentEquals(bytes, Files.readAllBytes(artifact))
        }
    }

    @Test
    fun `generation failures record safe codes and the open job recovers`() = runBlocking {
        migratedDataSource("production-artifact-failure-test").use { dataSource ->
            prepare(dataSource)
            val database = Database.connect(dataSource)
            val repository = ProductionRequestRepository(database)
            enqueue(database, repository, orderId = 30)
            var image: Path? = null
            var broken = false
            val worker =
                worker(database, repository) { orderId ->
                    if (broken) throw IllegalStateException("source gone")
                    order(orderId, image)
                }

            worker.runOnce()

            val missingImage = jobState(dataSource)
            assertEquals(1, missingImage.attempts)
            assertEquals("MISSING_IMAGE", missingImage.errorCode)
            assertNull(missingImage.contentSha256)
            assertNull(missingImage.generatedAt)
            assertTrue(Files.notExists(artifactRoot.resolve("${missingImage.id}")))

            broken = true
            worker.runOnce()

            val sourceGone = jobState(dataSource)
            assertEquals(2, sourceGone.attempts)
            assertEquals("SOURCE_UNAVAILABLE", sourceGone.errorCode)

            broken = false
            image = writePng(imageDirectory, "healed.png")
            worker.runOnce()

            val healed = jobState(dataSource)
            assertEquals(3, healed.attempts)
            assertNotNull(healed.generatedAt)
            assertNotNull(healed.contentSha256)
            assertNull(healed.errorCode)
        }
    }

    @Test
    fun `a crash between file write and database commit heals idempotently`() = runBlocking {
        migratedDataSource("production-artifact-crash-test").use { dataSource ->
            prepare(dataSource)
            val database = Database.connect(dataSource)
            val repository = ProductionRequestRepository(database)
            enqueue(database, repository, orderId = 40)
            var image: Path? = null
            val worker = worker(database, repository) { orderId -> order(orderId, image) }

            // First scan creates the open job but cannot generate yet.
            worker.runOnce()
            val open = jobState(dataSource)
            assertNull(open.generatedAt)

            // Simulate a crash after the file write: bytes exist, the database commit never ran.
            val artifact = artifactRoot.resolve("${open.id}").resolve("ORD-40.pdf")
            Files.createDirectories(artifact.parent)
            Files.write(artifact, "half a pdf from a crashed attempt".toByteArray())

            image = writePng(imageDirectory, "item.png")
            worker.runOnce()

            val healed = jobState(dataSource)
            val sha256 = assertNotNull(healed.contentSha256)
            val bytes = Files.readAllBytes(artifact)
            assertTrue(bytes.decodeToString(0, 5).startsWith("%PDF-"), "artifact is not a PDF")
            assertEquals(sha256, sha256Hex(bytes))
            val loaded = ProductionArtifactStore(artifactRoot).load(open.id, "ORD-40.pdf", sha256)
            assertContentEquals(bytes, assertIs<ProductionArtifactLoadResult.Loaded>(loaded).bytes)
        }
    }

    private fun worker(
        database: Database,
        repository: ProductionRequestRepository,
        source: ProductionSource,
    ): ProductionWorker =
        ProductionWorker(
            source = source,
            repository = repository,
            generator =
                ProductionArtifactGenerator(
                    source = source,
                    jobs = ProductionJobRepository(database),
                    renderer = ProductionPdfRenderer(),
                    artifacts = ProductionArtifactStore(artifactRoot),
                ),
            // No adapters: these tests inspect generation state; deliveries stay untouched
            // apart from a bounded UNSUPPORTED_CHANNEL retry code.
            deliverer =
                ProductionDeliverer(
                    repository =
                        ProductionDeliveryRepository(database) { reference ->
                            error("unexpected notification enqueue for $reference")
                        },
                    artifacts = ProductionArtifactStore(artifactRoot),
                    adapters = emptyList(),
                ),
        )

    private suspend fun enqueue(
        database: Database,
        repository: ProductionRequestRepository,
        orderId: Long,
    ): Long =
        withContext(Dispatchers.IO) {
            suspendTransaction(db = database) {
                maxAttempts = 1
                repository.requestInCurrentTransaction(orderId)
            }
        }

    private fun order(
        orderId: Long,
        imagePath: Path?,
        articleName: String = "Zaubertasse",
    ): ProductionData =
        ProductionData(
            orderId = orderId,
            orderDate = LocalDate.of(2026, 7, 16),
            shippingFirstName = "Erika",
            shippingLastName = "Musterfrau",
            shippingStreet = "Musterstraße",
            shippingHouseNumber = "1",
            shippingPostalCode = "12345",
            shippingCity = "Berlin",
            shippingCountry = "Deutschland",
            items =
                listOf(
                    ProductionItem(
                        supplierId = 1,
                        articleName = articleName,
                        supplierArticleNumber = null,
                        variantName = "Blau",
                        quantity = 1,
                        imagePath = imagePath,
                    )
                ),
        )

    private fun prepare(dataSource: DataSource) {
        execute(
            dataSource,
            "TRUNCATE voenix.production_deliveries, voenix.production_jobs, " +
                "voenix.production_requests, voenix.production_destinations, voenix.suppliers " +
                "RESTART IDENTITY CASCADE",
        )
        execute(dataSource, "INSERT INTO voenix.suppliers (id, name) VALUES (1, 'Supplier 1')")
        execute(
            dataSource,
            """
            INSERT INTO voenix.production_destinations
                (id, supplier_id, channel, label, host, username, password,
                 host_key_fingerprint, timeout_seconds)
            VALUES
                (1, 1, 'SFTP', 'Destination 1', 'sftp.example.com', 'user', 'secret',
                 'SHA256:fingerprint', 30)
            """
                .trimIndent(),
        )
    }

    private fun execute(dataSource: DataSource, sql: String) {
        dataSource.connection.use { connection ->
            connection.createStatement().use { statement -> statement.executeUpdate(sql) }
        }
    }

    private fun jobState(dataSource: DataSource): JobState =
        dataSource.connection.use { connection ->
            connection.createStatement().use { statement ->
                statement
                    .executeQuery(
                        "SELECT id, generation_attempt_count, last_generation_error_code, " +
                            "content_sha256, generated_at FROM voenix.production_jobs"
                    )
                    .use { rows ->
                        assertTrue(rows.next(), "expected exactly one production job")
                        val state =
                            JobState(
                                id = rows.getLong("id"),
                                attempts = rows.getInt("generation_attempt_count"),
                                errorCode = rows.getString("last_generation_error_code"),
                                contentSha256 = rows.getString("content_sha256"),
                                generatedAt = rows.getTimestamp("generated_at")?.toInstant(),
                            )
                        assertTrue(!rows.next(), "expected exactly one production job")
                        state
                    }
            }
        }

    private fun sha256Hex(bytes: ByteArray): String =
        HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes))

    private data class JobState(
        val id: Long,
        val attempts: Int,
        val errorCode: String?,
        val contentSha256: String?,
        val generatedAt: java.time.Instant?,
    )
}
