package shop.voenix

import io.ktor.client.request.get
import io.ktor.client.statement.bodyAsText
import io.ktor.http.HttpStatusCode
import io.ktor.server.config.MapApplicationConfig
import io.ktor.server.testing.testApplication
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertSame
import kotlin.test.assertTrue
import kotlinx.coroutines.runBlocking
import org.jetbrains.exposed.v1.jdbc.Database
import shop.voenix.country.CountryInput
import shop.voenix.country.CountryRepository
import shop.voenix.country.CountryResult
import shop.voenix.country.CountryService
import shop.voenix.testing.PostgresIntegrationTest

class ExistingSchemaAdoptionIntegrationTest : PostgresIntegrationTest() {
    @Test
    fun `startup safely adopts an equivalent ef country schema without replacing data`() {
        dataSource("existing-country-schema-setup").use { dataSource ->
            dataSource.connection.use { connection ->
                connection.createStatement().use { statement ->
                    statement.execute("DROP SCHEMA IF EXISTS \"select\" CASCADE")
                    statement.execute(
                        """
                        CREATE SCHEMA "select";
                        CREATE TABLE "select".countries (
                            id bigint GENERATED BY DEFAULT AS IDENTITY,
                            name character varying(255) NOT NULL,
                            country_code character varying(2) NOT NULL,
                            CONSTRAINT "PK_countries" PRIMARY KEY (id)
                        );
                        CREATE UNIQUE INDEX uk_countries_country_code
                            ON "select".countries (country_code);
                        CREATE UNIQUE INDEX ix_countries_name_lower
                            ON "select".countries (LOWER(name));
                        INSERT INTO "select".countries (name, country_code)
                            VALUES ('Portugal', 'PT');
                        CREATE TABLE "select".suppliers (
                            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            country_id bigint NULL,
                            CONSTRAINT "FK_suppliers_countries_country_id"
                                FOREIGN KEY (country_id)
                                REFERENCES "select".countries (id)
                                ON DELETE SET NULL
                        );
                        CREATE INDEX "IX_suppliers_country_id"
                            ON "select".suppliers (country_id);
                        INSERT INTO "select".suppliers (country_id) VALUES (1);
                        """
                            .trimIndent()
                    )
                }
            }
        }

        testApplication {
            environment { config = applicationConfig("select") }
            application { module() }

            val response = client.get("/api/countries")
            assertEquals(HttpStatusCode.OK, response.status)
            assertTrue(response.bodyAsText().contains("Portugal"))
            assertTrue(!response.bodyAsText().contains("Germany"))
        }

        dataSource("existing-country-schema-verification", "select").use { dataSource ->
            val service =
                CountryService(CountryRepository(Database.connect(datasource = dataSource)))
            runBlocking {
                assertSame(
                    CountryResult.NameConflict,
                    service.create(CountryInput("portugal", "PX")),
                )
                assertSame(
                    CountryResult.CodeConflict,
                    service.create(CountryInput("Spain", "pt")),
                )
            }

            dataSource.connection.use { connection ->
                connection.createStatement().use { statement ->
                    statement.execute(
                        """
                        CREATE UNIQUE INDEX unexpected_countries_name_initial
                            ON "select".countries ((LEFT(LOWER(name), 1)))
                        """
                            .trimIndent()
                    )
                }
            }
            assertSame(
                CountryResult.DatabaseError,
                runBlocking { service.create(CountryInput("Peru", "PE")) },
            )

            dataSource.connection.use { connection ->
                val countryCount =
                    connection.prepareStatement("SELECT COUNT(*) FROM \"select\".countries").use {
                        statement ->
                        statement.executeQuery().use { rows ->
                            rows.next()
                            rows.getInt(1)
                        }
                    }
                assertEquals(1, countryCount)

                val baselineCount =
                    connection
                        .prepareStatement(
                            """
                            SELECT COUNT(*)
                            FROM "select".flyway_schema_history
                            WHERE version = '1' AND type = 'BASELINE' AND success
                            """
                                .trimIndent()
                        )
                        .use { statement ->
                            statement.executeQuery().use { rows ->
                                rows.next()
                                rows.getInt(1)
                            }
                        }
                assertEquals(1, baselineCount)

                connection.prepareStatement("DELETE FROM \"select\".countries WHERE id = 1").use {
                    statement ->
                    assertEquals(1, statement.executeUpdate())
                }
                val supplierCountryId =
                    connection
                        .prepareStatement("SELECT country_id FROM \"select\".suppliers")
                        .use { statement ->
                            statement.executeQuery().use { rows ->
                                rows.next()
                                rows.getObject(1)
                            }
                        }
                assertEquals(null, supplierCountryId)
            }
        }
    }

    @Test
    fun `startup refuses to baseline a same-named unique index that is not a primary key`() {
        dataSource("incompatible-country-schema-setup").use { dataSource ->
            dataSource.connection.use { connection ->
                connection.createStatement().use { statement ->
                    statement.execute("DROP SCHEMA IF EXISTS adoption_test CASCADE")
                    statement.execute(
                        """
                        CREATE SCHEMA adoption_test;
                        CREATE TABLE adoption_test.countries (
                            id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            name character varying(255) NOT NULL,
                            country_code character varying(2) NOT NULL
                        );
                        CREATE UNIQUE INDEX "PK_countries" ON adoption_test.countries (id);
                        CREATE UNIQUE INDEX uk_countries_country_code
                            ON adoption_test.countries (country_code);
                        CREATE UNIQUE INDEX ix_countries_name_lower
                            ON adoption_test.countries (LOWER(name));
                        """
                            .trimIndent()
                    )
                }
            }
        }

        val failure =
            assertFailsWith<IllegalStateException> {
                testApplication {
                    environment { config = applicationConfig("adoption_test") }
                    application { module() }
                    client.get("/api/countries")
                }
            }
        assertTrue(failure.message.orEmpty().contains("constraints"))
    }

    private fun applicationConfig(schema: String): MapApplicationConfig =
        MapApplicationConfig().apply {
            put("Database.Host", postgres.host)
            put("Database.Port", postgres.firstMappedPort.toString())
            put("Database.Database", postgres.databaseName)
            put("Database.Username", postgres.username)
            put("Database.Password", postgres.password)
            put("Database.SearchPath", schema)
            put("Database.SslMode", "Disable")
            put("Database.MaximumPoolSize", "2")
            put("Auth.SessionSecret", "existing-schema-test-session-secret")
        }
}
