package shop.voenix.production.fulfillment

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import shop.voenix.production.delivery.ProductionChannels
import shop.voenix.production.delivery.spod.SpodOrderRepository
import shop.voenix.production.delivery.spod.SpodRemoteStates
import shop.voenix.production.delivery.spod.parseSpodOrderReference
import shop.voenix.production.pdf.ProductionArtifactLoadResult
import shop.voenix.production.pdf.ProductionArtifactStore
import shop.voenix.supplier.SupplierReader
import shop.voenix.supplier.SupplierSummary

/**
 * Assembles a fulfillment page out of the three things it is made of: the job rows, the order
 * headers behind them, and the item lines snapshotted with them at split time — and performs the
 * one write of this surface, the shipment.
 *
 * The batching rule is the whole performance contract of this class, and it lives in one place: a
 * read loads its jobs, hands them to [batch], and every view is built from that one structure.
 * [batch] resolves *all* order ids with one [FulfillmentOrderSource] call and reads *all* items
 * with one repository call; the admin list — the only one that shows supplier names — resolves
 * *all* supplier ids with one [SupplierReader] call before it maps. No loop here ever calls out,
 * and the non-suspend view lambdas of [FulfillmentBatch] turn an attempt to do so into a compile
 * error.
 *
 * The two policies for a job whose order header the order module cannot answer for sit next to each
 * other in [FulfillmentBatch]: a list drops the row and logs it, because rendering an address-less
 * shipping label would be worse than a missing row; the single answer of a ship request throws,
 * because the shipment is already committed at that point and a missing header is a broken foreign
 * key. The foreign keys make both cases impossible in practice.
 *
 * Shipping is one path for both surfaces: the supplier passes its own id as the scope, the admin
 * passes `null`, and everything that decides the outcome happens in the repository's guarded
 * update. What differs between the two is only the view the answer is rendered as.
 *
 * The print-on-demand partner is the third caller of that same path, through
 * [SpodWebhookOperations]. It reports a shipment nobody in this shop pressed a button for, so the
 * write records the channel instead of a user — and everything else about it is identical, down to
 * the customer's mail. That is why the webhook lives on this class rather than beside it: a second
 * implementation of "a job is shipped" is exactly the thing that would drift.
 */
internal class FulfillmentService(
    private val repository: FulfillmentRepository,
    private val orders: FulfillmentOrderSource,
    private val suppliers: SupplierReader,
    private val artifacts: ProductionArtifactStore,
    private val spodOrders: SpodOrderRepository,
) : FulfillmentOperations, SpodWebhookOperations {
    override suspend fun identity(supplierId: Long): SupplierIdentityView {
        val supplier =
            checkNotNull(suppliers.find(setOf(supplierId))[supplierId]) {
                "Supplier $supplierId has a login but no supplier row"
            }
        return SupplierIdentityView(supplierId = supplier.id, supplierName = supplier.name)
    }

    override suspend fun supplierJobs(
        supplierId: Long,
        status: FulfillmentJobStatus,
    ): List<SupplierJobView> {
        val jobs = repository.jobs(status, supplierId)
        if (jobs.isEmpty()) return emptyList()
        return batch(jobs).listed(::supplierJobView)
    }

    override suspend fun adminJobs(
        status: FulfillmentJobStatus,
        supplierId: Long?,
    ): List<AdminJobView> {
        val jobs = repository.jobs(status, supplierId)
        if (jobs.isEmpty()) return emptyList()
        val names = suppliers.find(jobs.mapTo(mutableSetOf(), StoredFulfillmentJob::supplierId))
        return batch(jobs).listed { job, header, items ->
            adminJobView(
                job = job,
                header = header,
                items = items,
                supplierName = names[job.supplierId]?.let(SupplierSummary::name),
            )
        }
    }

    /**
     * Loads the stored artifact and verifies it against the digest written at generation time, so a
     * download either ships exactly the generated bytes or says why it cannot.
     *
     * A job of a channel that produces no document has no artifact resource at all, and it answers
     * like any other address that does not exist: `NotFound`. The three conflict states below are
     * about a document that is late, gone, or wrong — promising one of them for a job that will
     * never have a PDF would tell the caller to come back later, forever.
     */
    override suspend fun artifact(jobId: Long, supplierScope: Long?): FulfillmentArtifactResult {
        val job = repository.job(jobId, supplierScope) ?: return FulfillmentArtifactResult.NotFound
        if (job.fulfillmentChannel != ProductionChannels.SFTP) {
            return FulfillmentArtifactResult.NotFound
        }
        val sha256 = job.contentSha256 ?: return FulfillmentArtifactResult.NotGenerated
        val loaded = withContext(Dispatchers.IO) { artifacts.load(job.id, job.fileName, sha256) }
        return when (loaded) {
            is ProductionArtifactLoadResult.Loaded ->
                FulfillmentArtifactResult.Loaded(job.fileName, loaded.bytes)
            ProductionArtifactLoadResult.Missing -> {
                logger.error("Production job {} has a digest but no artifact file", job.id)
                FulfillmentArtifactResult.Missing
            }
            is ProductionArtifactLoadResult.DigestMismatch -> {
                logger.error(
                    "Production job {} artifact does not match its recorded digest",
                    job.id,
                )
                FulfillmentArtifactResult.DigestMismatch
            }
        }
    }

    override suspend fun shipAsSupplier(
        jobId: Long,
        supplierId: Long,
        actorUserId: Long,
        shipment: Shipment,
    ): ShipResult<SupplierJobView> =
        ship(jobId, actorUserId, supplierScope = supplierId, shipment = shipment).mapShipped { job
            ->
            batch(listOf(job)).only(::supplierJobView)
        }

    override suspend fun shipAsAdmin(
        jobId: Long,
        actorUserId: Long,
        shipment: Shipment,
    ): ShipResult<AdminJobView> =
        ship(jobId, actorUserId, supplierScope = null, shipment = shipment).mapShipped { job ->
            // Resolved before the mapping, like the admin list resolves its page's names: the view
            // lambda below cannot call out.
            val supplierName = suppliers.find(setOf(job.supplierId))[job.supplierId]?.name
            batch(listOf(job)).only { shipped, header, items ->
                adminJobView(
                    job = shipped,
                    header = header,
                    items = items,
                    supplierName = supplierName,
                )
            }
        }

    /**
     * One event the print-on-demand partner reported, applied to the job it names.
     *
     * Every branch may end in nothing at all, and none of them says so: the partner is told `202`
     * either way, because an unknown reference and a job that shipped hours ago are both states a
     * redelivery would not improve. What each branch does *not* do is act twice — the shipment runs
     * through the very same guarded transaction a human ship uses, and the remote state is written
     * with an idempotent enqueue beside it.
     */
    override suspend fun handle(event: SpodWebhookEvent) {
        val jobId = resolveJob(event.reference)
        if (jobId == null) {
            logger.warn("A SPOD webhook event named no production job of this shop")
            return
        }
        when (event) {
            is SpodWebhookEvent.ShipmentSent -> shipReported(jobId, event)
            is SpodWebhookEvent.RemoteStateReported ->
                spodOrders.recordRemoteState(jobId, event.state.stored())
        }
    }

    /**
     * The reported shipment through the one guarded ship transaction of this module.
     *
     * A refusal is logged at error level, not at info: the partner is acknowledged either way and
     * never redelivers, so a shipment this shop declined to store is a shipment nobody will ever
     * report again. Only [ShipWriteResult.ALREADY_SHIPPED] is ordinary — that is a redelivery
     * arriving at a job this shop already shipped, which is the webhook working as designed.
     */
    private suspend fun shipReported(jobId: Long, event: SpodWebhookEvent.ShipmentSent) {
        val result =
            repository.ship(
                jobId = jobId,
                actor = ShipActor.Channel(ProductionChannels.SPOD),
                supplierScope = null,
                shipment =
                    Shipment(
                        carrier = event.carrier,
                        trackingNumber = event.trackingNumber,
                        reportedCarrierName = event.reportedCarrier,
                    ),
            )
        when (result) {
            ShipWriteResult.SHIPPED,
            ShipWriteResult.ALREADY_SHIPPED ->
                logger.info("Production job {} reported as shipped by SPOD: {}", jobId, result)
            ShipWriteResult.NOT_FOUND,
            ShipWriteResult.NOT_READY ->
                logger.error(
                    "Production job {}: SPOD reported a shipment this shop could not store ({})",
                    jobId,
                    result,
                )
        }
    }

    /**
     * The job a reported event is about: the partner's own order id first, this shop's reference
     * second.
     *
     * The fallback is not a second lookup of the same thing. The partner's id is stored only after
     * a creation this backend saw the answer of, so a job whose creation ended ambiguously has none
     * — and its reference is exactly the string that still finds it. It is checked, though: the ids
     * in an untrusted body must match a job that really is a print-on-demand job of the order they
     * claim.
     */
    private suspend fun resolveJob(reference: SpodOrderReference): Long? =
        reference.externalReference?.let { external ->
            spodOrders.jobIdOfExternalReference(external)
        } ?: reference.shopReference?.let { shopReference -> resolveShopReference(shopReference) }

    private suspend fun resolveShopReference(shopReference: String): Long? {
        val ids = parseSpodOrderReference(shopReference) ?: return null
        val job = repository.job(ids.jobId, supplierScope = null) ?: return null
        return ids.jobId.takeIf {
            job.orderId == ids.orderId && job.fulfillmentChannel == ProductionChannels.SPOD
        }
    }

    /**
     * The one ship path of both surfaces. The repository decides the outcome in a single guarded
     * transaction; a success is read back so the answer shows the shipment that was just stored
     * rather than the values this process happens to hold.
     */
    private suspend fun ship(
        jobId: Long,
        actorUserId: Long,
        supplierScope: Long?,
        shipment: Shipment,
    ): ShipResult<StoredFulfillmentJob> =
        when (repository.ship(jobId, ShipActor.User(actorUserId), supplierScope, shipment)) {
            ShipWriteResult.NOT_FOUND -> ShipResult.NotFound
            ShipWriteResult.ALREADY_SHIPPED -> ShipResult.AlreadyShipped
            ShipWriteResult.NOT_READY -> ShipResult.NotReady
            ShipWriteResult.SHIPPED ->
                ShipResult.Shipped(
                    checkNotNull(repository.job(jobId, supplierScope)) {
                        "Production job $jobId vanished right after it was shipped"
                    }
                )
        }

    /**
     * The one loader of this class: whatever set of jobs is to be rendered — a whole page or the
     * single job a ship request just wrote — with its order headers read in one
     * [FulfillmentOrderSource] call and its item lines in one repository call.
     */
    private suspend fun batch(jobs: List<StoredFulfillmentJob>): FulfillmentBatch =
        FulfillmentBatch(
            jobs = jobs,
            headers = orders.find(jobs.mapTo(mutableSetOf(), StoredFulfillmentJob::orderId)),
            items = repository.items(jobs.mapTo(mutableSetOf(), StoredFulfillmentJob::id)),
        )

    /**
     * One batch of jobs plus everything their views are built from, with the two ways of rendering
     * it side by side: [listed] for a page, [only] for the single answer of a ship request. They
     * differ in exactly one decision — what a missing order header means.
     *
     * The `view` lambdas are deliberately **not** `suspend`: a call-out from inside a mapping is
     * the failure mode a batched read falls into silently, and here it does not compile. Everything
     * a view needs beyond this batch — the admin's supplier names — is resolved before the call.
     */
    private class FulfillmentBatch(
        private val jobs: List<StoredFulfillmentJob>,
        private val headers: Map<Long, FulfillmentOrder>,
        private val items: Map<Long, List<StoredFulfillmentJob.Item>>,
    ) {
        /**
         * The page. A job whose order header is missing is logged and dropped: the rest of the page
         * is worth more than an answer that fails as a whole, and a label without an address would
         * be worse than a missing row.
         */
        fun <V> listed(
            view: (StoredFulfillmentJob, FulfillmentOrder, List<FulfillmentItemView>) -> V
        ): List<V> = jobs.mapNotNull { job ->
            val header = headers[job.orderId]
            if (header == null) {
                logger.error(
                    "Production job {} names order {}, which no longer exists",
                    job.id,
                    job.orderId,
                )
                null
            } else {
                view(job, header, itemViewsOf(job))
            }
        }

        /**
         * The single job of a committed shipment. Unlike a page, this answer cannot drop the row: a
         * missing header is a broken foreign key and must be loud rather than an empty answer to a
         * write that already happened.
         */
        fun <V> only(
            view: (StoredFulfillmentJob, FulfillmentOrder, List<FulfillmentItemView>) -> V
        ): V {
            val job = jobs.single()
            val header =
                checkNotNull(headers[job.orderId]) {
                    "Production job ${job.id} names order ${job.orderId}, which no longer exists"
                }
            return view(job, header, itemViewsOf(job))
        }

        /** The job's item lines, in printing order. */
        private fun itemViewsOf(job: StoredFulfillmentJob): List<FulfillmentItemView> =
            items[job.id].orEmpty().toItemViews()
    }

    private companion object {
        val logger: Logger = LoggerFactory.getLogger(FulfillmentService::class.java)
    }
}

/** Turns a successful shipment into the view of the surface that asked; failures pass through. */
private suspend fun <V> ShipResult<StoredFulfillmentJob>.mapShipped(
    view: suspend (StoredFulfillmentJob) -> V
): ShipResult<V> =
    when (this) {
        is ShipResult.Shipped -> ShipResult.Shipped(view(job))
        ShipResult.NotFound -> ShipResult.NotFound
        ShipResult.AlreadyShipped -> ShipResult.AlreadyShipped
        ShipResult.NotReady -> ShipResult.NotReady
    }

private fun List<StoredFulfillmentJob.Item>.toItemViews(): List<FulfillmentItemView> =
    sortedBy(StoredFulfillmentJob.Item::position).map { item ->
        FulfillmentItemView(
            articleName = item.articleName,
            variantName = item.variantName,
            supplierArticleNumber = item.supplierArticleNumber,
            quantity = item.quantity,
        )
    }

private fun supplierJobView(
    job: StoredFulfillmentJob,
    header: FulfillmentOrder,
    items: List<FulfillmentItemView>,
): SupplierJobView =
    SupplierJobView(
        jobId = job.id,
        orderId = header.orderId,
        orderDate = header.orderDate.toString(),
        customerFirstName = header.customerFirstName,
        customerLastName = header.customerLastName,
        shippingStreet = header.shippingStreet,
        shippingHouseNumber = header.shippingHouseNumber,
        shippingPostalCode = header.shippingPostalCode,
        shippingCity = header.shippingCity,
        shippingCountry = header.shippingCountry,
        items = items,
        pdfAvailable = job.generatedAt != null,
        shippedAt = job.shippedAt?.toInstant(),
        shippingCarrier = job.shippingCarrier,
        trackingNumber = job.trackingNumber,
    )

private fun adminJobView(
    job: StoredFulfillmentJob,
    header: FulfillmentOrder,
    items: List<FulfillmentItemView>,
    supplierName: String?,
): AdminJobView =
    AdminJobView(
        jobId = job.id,
        orderId = header.orderId,
        orderDate = header.orderDate.toString(),
        supplier = AdminJobView.Supplier(id = job.supplierId, name = supplierName),
        customerFirstName = header.customerFirstName,
        customerLastName = header.customerLastName,
        shippingStreet = header.shippingStreet,
        shippingHouseNumber = header.shippingHouseNumber,
        shippingPostalCode = header.shippingPostalCode,
        shippingCity = header.shippingCity,
        shippingCountry = header.shippingCountry,
        items = items,
        fulfillmentChannel = job.fulfillmentChannel,
        pdfAvailable = job.generatedAt != null,
        generationAttemptCount = job.generationAttemptCount,
        lastGenerationErrorCode = job.lastGenerationErrorCode,
        externalReference = job.externalReference,
        remoteState = job.remoteState,
        shippedAt = job.shippedAt?.toInstant(),
        shippedByUserId = job.shippedByUserId,
        shippedByChannel = job.shippedByChannel,
        shippingCarrier = job.shippingCarrier,
        shippingCarrierReported = job.shippingCarrierReported,
        trackingNumber = job.trackingNumber,
    )

/** The `remote_state` value one reported state is stored as. */
private fun SpodReportedState.stored(): String =
    when (this) {
        SpodReportedState.CANCELLED -> SpodRemoteStates.CANCELLED
        SpodReportedState.NEEDS_ACTION -> SpodRemoteStates.NEEDS_ACTION
    }
