-- user_id deliberately has no foreign key yet: the users table arrives with the
-- Auth/User migration (see docs/migration/magic-coins-migration.md).
CREATE TABLE magic_coins (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    guest_session_token text,
    user_id bigint,
    balance integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_magic_coins PRIMARY KEY (id),
    CONSTRAINT ck_magic_coins_exactly_one_owner
        CHECK ((guest_session_token IS NOT NULL) <> (user_id IS NOT NULL)),
    CONSTRAINT ck_magic_coins_balance_non_negative CHECK (balance >= 0)
);

CREATE UNIQUE INDEX ux_magic_coins_guest_session_token
    ON magic_coins (guest_session_token)
    WHERE guest_session_token IS NOT NULL;

CREATE UNIQUE INDEX ux_magic_coins_user_id
    ON magic_coins (user_id)
    WHERE user_id IS NOT NULL;
