CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255) NOT NULL,
    email_confirmed boolean NOT NULL DEFAULT false,
    password_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    failed_login_count integer NOT NULL DEFAULT 0,
    locked_until timestamptz,
    shipping_first_name character varying(100),
    shipping_last_name character varying(100),
    shipping_street character varying(200),
    shipping_house_number character varying(20),
    shipping_postal_code character varying(10),
    shipping_city character varying(100),
    shipping_country character varying(2),
    shipping_phone text,
    billing_first_name character varying(100),
    billing_last_name character varying(100),
    billing_street character varying(200),
    billing_house_number character varying(20),
    billing_postal_code character varying(10),
    billing_city character varying(100),
    billing_country character varying(2),
    billing_phone text,
    has_separate_billing_address boolean NOT NULL DEFAULT false,
    -- Set for a supplier login only: it binds the user to the one supplier whose
    -- production jobs they may see and ship. Customers and admins leave it NULL.
    supplier_id bigint,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT ck_users_failed_login_count_non_negative CHECK (failed_login_count >= 0),
    -- RESTRICT: a supplier with logins cannot be deleted; the supplier module
    -- turns the violation into its existing 409.
    CONSTRAINT fk_users_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE RESTRICT
);

-- Only supplier logins carry the link, so the index only carries them too.
CREATE INDEX ix_users_supplier_id ON users (supplier_id) WHERE supplier_id IS NOT NULL;

-- The e-mail doubles as the login name; uniqueness is case-insensitive so the
-- database, not a preliminary lookup, is the concurrency-safe authority.
CREATE UNIQUE INDEX ux_users_email_lower
    ON users (LOWER(email));

CREATE TABLE user_roles (
    user_id bigint NOT NULL,
    role text NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Single-use e-mail action tokens (account confirmation, password reset,
-- e-mail change). Only the SHA-256 hash of the mailed token is stored; the
-- unique (user_id, purpose) rule enforces that only the latest link of a kind
-- counts. Consuming a token deletes its row.
CREATE TABLE account_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    purpose text NOT NULL,
    token_hash text NOT NULL,
    new_email character varying(255),
    expires_at timestamptz NOT NULL,
    CONSTRAINT pk_account_tokens PRIMARY KEY (id),
    CONSTRAINT fk_account_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ux_account_tokens_user_purpose UNIQUE (user_id, purpose)
);

-- Deferred by the MagicCoins migration until the users table exists
-- (see docs/migration/magic-coins-migration.md).
ALTER TABLE magic_coins
    ADD CONSTRAINT fk_magic_coins_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

-- Deferred by the production jobs migration for the same reason: the shipping
-- record points at the user who shipped, and that table only exists here. The
-- shipment itself stays intact when the login is deleted, so the reference is
-- cleared instead of blocking the delete.
ALTER TABLE production_jobs
    ADD CONSTRAINT fk_production_jobs_shipped_by_user
        FOREIGN KEY (shipped_by_user_id) REFERENCES users (id) ON DELETE SET NULL;
