CREATE TABLE promotions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    discount_type text NOT NULL,
    discount_value numeric(12, 2) NOT NULL,
    coupon_code character varying(64) NOT NULL,
    coupon_code_normalized character varying(64) NOT NULL,
    starts_at timestamptz NULL,
    ends_at timestamptz NULL,
    usage_limit_total integer NULL,
    usage_limit_per_user integer NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_promotions PRIMARY KEY (id),
    CONSTRAINT ck_promotions_discount_type
        CHECK (discount_type IN ('PERCENTAGE', 'FIXED_AMOUNT')),
    CONSTRAINT ck_promotions_discount_value_positive CHECK (discount_value > 0),
    CONSTRAINT ck_promotions_usage_limit_total_positive
        CHECK (usage_limit_total IS NULL OR usage_limit_total > 0),
    CONSTRAINT ck_promotions_usage_limit_per_user_positive
        CHECK (usage_limit_per_user IS NULL OR usage_limit_per_user > 0),
    CONSTRAINT ux_promotions_coupon_code_normalized UNIQUE (coupon_code_normalized)
);

CREATE INDEX ix_promotions_name ON promotions (name);

-- order_id deliberately does not exist yet: the orders table arrives with the
-- Order migration, which adds the column and its foreign key (see
-- docs/migration/promotion-migration.md).
CREATE TABLE promotion_redemptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    promotion_id bigint NOT NULL,
    user_id bigint NULL,
    redeemed_at timestamptz NOT NULL,
    CONSTRAINT pk_promotion_redemptions PRIMARY KEY (id),
    CONSTRAINT fk_promotion_redemptions_promotion
        FOREIGN KEY (promotion_id) REFERENCES promotions (id) ON DELETE RESTRICT
);

CREATE INDEX ix_promotion_redemptions_promotion_id
    ON promotion_redemptions (promotion_id);
CREATE INDEX ix_promotion_redemptions_promotion_id_user_id
    ON promotion_redemptions (promotion_id, user_id);
