-- The article schema of the Article migration (docs/migration/article-migration.md).
--
-- Three ideas shape it:
--
-- 1. One table per article type. `article_mugs` merges the legacy `articles` and
--    `article_mug_details` rows; a future type gets its own table instead of more
--    nullable columns in a shared one.
-- 2. Two identity registries give Cart, Order, and every other consumer one
--    foreign-key target across all article types. They carry no business data and
--    never gain another column.
-- 3. Every invariant PostgreSQL can express lives here, declaratively. There are
--    deliberately no triggers: cross-row rules (at least one default variant, an
--    active article needs an active variant, dense positions) live in the single
--    application write path.

-- The known article types. This is the foreign-key target of the identity
-- registry and the ordering lock anchor for per-type article positions: a
-- transaction that writes `article_mugs.position` first locks the `MUG` row.
CREATE TABLE article_types (
    article_type text NOT NULL,
    CONSTRAINT pk_article_types PRIMARY KEY (article_type)
);

INSERT INTO article_types (article_type) VALUES ('MUG');

-- The ordering lock anchor of the type-agnostic taxonomy. Category positions are
-- global, so every transaction that writes one (create, delete compaction,
-- reorder) first takes `SELECT ... FOR UPDATE` on this single row and therefore
-- queues behind every other position writer. The table holds no data; the row is
-- the lock.
CREATE TABLE article_taxonomy_state (
    id integer NOT NULL,
    CONSTRAINT pk_article_taxonomy_state PRIMARY KEY (id),
    CONSTRAINT ck_article_taxonomy_state_single_row CHECK (id = 1)
);

INSERT INTO article_taxonomy_state (id) VALUES (1);

-- The article identity of every type. `id` is minted here, so Cart and Order can
-- reference one article across per-type tables. UNIQUE (id, article_type) is the
-- alternate key that lets a type table prove its row is registered as that type.
CREATE TABLE article_identities (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    article_type text NOT NULL,
    CONSTRAINT pk_article_identities PRIMARY KEY (id),
    CONSTRAINT ak_article_identities_id_article_type UNIQUE (id, article_type),
    CONSTRAINT fk_article_identities_article_type
        FOREIGN KEY (article_type)
        REFERENCES article_types (article_type)
        ON DELETE RESTRICT
);

-- The variant identity of every type. The composite foreign key makes "this
-- variant belongs to that article" a database fact, and UNIQUE (id, article_id)
-- lets a type table prove the same about its own variant row.
CREATE TABLE article_variant_identities (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    article_id bigint NOT NULL,
    article_type text NOT NULL,
    CONSTRAINT pk_article_variant_identities PRIMARY KEY (id),
    CONSTRAINT ak_article_variant_identities_id_article_id UNIQUE (id, article_id),
    CONSTRAINT fk_article_variant_identities_article
        FOREIGN KEY (article_id, article_type)
        REFERENCES article_identities (id, article_type)
        ON DELETE CASCADE
);

CREATE INDEX ix_article_variant_identities_article_id
    ON article_variant_identities (article_id);

-- The type-agnostic taxonomy. Names are unique case-insensitively, so "Mugs" and
-- "mugs" cannot coexist. Positions are dense and unique, but their unique rule is
-- DEFERRABLE INITIALLY DEFERRED: a reorder rewrites the sequence in one phase and
-- PostgreSQL checks the result only at COMMIT.
CREATE TABLE article_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(200) NOT NULL,
    description character varying(1000) NULL,
    position integer NOT NULL,
    active boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_article_categories PRIMARY KEY (id),
    CONSTRAINT ck_article_categories_position_positive CHECK (position > 0),
    CONSTRAINT ux_article_categories_position UNIQUE (position)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE UNIQUE INDEX ux_article_categories_name_lower
    ON article_categories (LOWER(name));

CREATE TABLE article_subcategories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    category_id bigint NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(1000) NULL,
    example_image_filename character varying(255) NULL,
    position integer NOT NULL,
    active boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_article_subcategories PRIMARY KEY (id),
    CONSTRAINT ak_article_subcategories_id_category_id UNIQUE (id, category_id),
    CONSTRAINT fk_article_subcategories_category
        FOREIGN KEY (category_id)
        REFERENCES article_categories (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_article_subcategories_position_positive CHECK (position > 0),
    CONSTRAINT ux_article_subcategories_category_position UNIQUE (category_id, position)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE UNIQUE INDEX ux_article_subcategories_category_name_lower
    ON article_subcategories (category_id, LOWER(name));

-- Mugs: the legacy `articles` row and its `article_mug_details` row in one table.
--
-- `article_type` is a constant column, not data. Together with the composite
-- foreign key it proves that this row's identity is registered as a mug, so a
-- mug can never claim the identity of another article type.
CREATE TABLE article_mugs (
    id bigint NOT NULL,
    article_type text NOT NULL DEFAULT 'MUG',
    position integer NOT NULL,
    name character varying(255) NOT NULL,
    description_short character varying(1000) NOT NULL,
    description_long character varying(5000) NOT NULL,
    active boolean NOT NULL,
    category_id bigint NULL,
    subcategory_id bigint NULL,
    supplier_id bigint NULL,
    supplier_article_name character varying(255) NULL,
    supplier_article_number character varying(255) NULL,
    price_id bigint NULL,
    height_mm integer NULL,
    diameter_mm integer NULL,
    print_template_width_mm integer NULL,
    print_template_height_mm integer NULL,
    filling_quantity character varying(255) NULL,
    dishwasher_safe boolean NULL,
    document_format_width_mm integer NULL,
    document_format_height_mm integer NULL,
    document_format_margin_bottom_mm integer NULL,
    CONSTRAINT pk_article_mugs PRIMARY KEY (id),
    CONSTRAINT ck_article_mugs_article_type CHECK (article_type = 'MUG'),
    CONSTRAINT fk_article_mugs_identity
        FOREIGN KEY (id, article_type)
        REFERENCES article_identities (id, article_type)
        ON DELETE CASCADE,
    CONSTRAINT fk_article_mugs_category
        FOREIGN KEY (category_id)
        REFERENCES article_categories (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_article_mugs_subcategory
        FOREIGN KEY (subcategory_id, category_id)
        REFERENCES article_subcategories (id, category_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_article_mugs_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_article_mugs_price
        FOREIGN KEY (price_id)
        REFERENCES prices (id)
        ON DELETE RESTRICT,
    -- A price belongs to exactly one article. Ownership already holds by
    -- construction, because no article contract accepts a price id; this is the
    -- backstop that makes it a database fact.
    CONSTRAINT ux_article_mugs_price_id UNIQUE (price_id),
    CONSTRAINT ck_article_mugs_position_positive CHECK (position > 0),
    CONSTRAINT ux_article_mugs_position UNIQUE (position)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT ck_article_mugs_subcategory_requires_category
        CHECK (subcategory_id IS NULL OR category_id IS NOT NULL),
    -- Mug details are one value: either the article carries all required
    -- measurements or it carries none of them. The optional detail fields exist
    -- only next to the required ones.
    CONSTRAINT ck_article_mugs_details_all_or_none CHECK (
        (
            height_mm IS NOT NULL
            AND diameter_mm IS NOT NULL
            AND print_template_width_mm IS NOT NULL
            AND print_template_height_mm IS NOT NULL
            AND dishwasher_safe IS NOT NULL
        )
        OR (
            height_mm IS NULL
            AND diameter_mm IS NULL
            AND print_template_width_mm IS NULL
            AND print_template_height_mm IS NULL
            AND dishwasher_safe IS NULL
            AND filling_quantity IS NULL
            AND document_format_width_mm IS NULL
            AND document_format_height_mm IS NULL
            AND document_format_margin_bottom_mm IS NULL
        )
    ),
    CONSTRAINT ck_article_mugs_measurements_positive CHECK (
        (height_mm IS NULL OR height_mm > 0)
        AND (diameter_mm IS NULL OR diameter_mm > 0)
        AND (print_template_width_mm IS NULL OR print_template_width_mm > 0)
        AND (print_template_height_mm IS NULL OR print_template_height_mm > 0)
        AND (document_format_width_mm IS NULL OR document_format_width_mm > 0)
        AND (document_format_height_mm IS NULL OR document_format_height_mm > 0)
        AND (
            document_format_margin_bottom_mm IS NULL
            OR document_format_margin_bottom_mm > 0
        )
    ),
    -- A visible article must be complete: it has a price, it has its mug
    -- details, and it sits in a category. Requiring the category is new
    -- behavior; the legacy storefront silently hid such articles.
    CONSTRAINT ck_article_mugs_active_requires_price_details_category CHECK (
        NOT active
        OR (
            price_id IS NOT NULL
            AND category_id IS NOT NULL
            AND height_mm IS NOT NULL
        )
    )
);

CREATE INDEX ix_article_mugs_category_id ON article_mugs (category_id);
CREATE INDEX ix_article_mugs_subcategory_id ON article_mugs (subcategory_id, category_id);
CREATE INDEX ix_article_mugs_supplier_id ON article_mugs (supplier_id);

CREATE TABLE article_mug_variants (
    id bigint NOT NULL,
    article_id bigint NOT NULL,
    inside_color_code character varying(255) NOT NULL,
    outside_color_code character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    is_default boolean NOT NULL,
    active boolean NOT NULL,
    example_image_filename character varying(255) NULL,
    CONSTRAINT pk_article_mug_variants PRIMARY KEY (id),
    CONSTRAINT fk_article_mug_variants_identity
        FOREIGN KEY (id, article_id)
        REFERENCES article_variant_identities (id, article_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_article_mug_variants_article
        FOREIGN KEY (article_id)
        REFERENCES article_mugs (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_article_mug_variants_article_id ON article_mug_variants (article_id);

-- At most one default variant per article. The other half of the rule — an
-- article with variants has at least one default — is a cross-row invariant and
-- belongs to the application write path.
CREATE UNIQUE INDEX ux_article_mug_variants_default
    ON article_mug_variants (article_id)
    WHERE is_default;
