-- The prompt schema of the Prompt migration (docs/migration/prompt-migration.md).
--
-- The whole schema is created here, in one migration, although the Kotlin module
-- arrives in three slices. The counts the first slice already answers with --
-- how many variants a slot has, how many prompts a variant is assigned to --
-- would otherwise be lies until the last slice lands, so the tables they count
-- exist from the start. Later slices add Kotlin only.
--
-- Three ideas shape it:
--
-- 1. Every invariant PostgreSQL can express lives here, declaratively. There are
--    deliberately no triggers.
-- 2. Positions are decided under a lock anchor, never by a preliminary read, and
--    their unique rules are DEFERRABLE INITIALLY DEFERRED. A reorder can then
--    rewrite a whole sequence in one phase, and a unique violation raised while a
--    statement runs provably means a *name* conflict.
-- 3. Names are unique case-insensitively, so "Background" and "background" cannot
--    coexist. Slot-variant names are unique across all slots on purpose: a variant
--    should exist exactly once, whatever slot it fills.

-- The ordering lock anchors of the three global position sequences. The table
-- holds no data; the rows are the locks. A transaction that writes a slot,
-- category, or prompt position first takes `SELECT ... FOR UPDATE` on its row and
-- therefore queues behind every other writer of that sequence.
--
-- Subcategory positions count per category, so their anchor is the category row
-- itself and not a row here.
CREATE TABLE prompt_ordering (
    sequence text NOT NULL,
    CONSTRAINT pk_prompt_ordering PRIMARY KEY (sequence),
    CONSTRAINT ck_prompt_ordering_sequence
        CHECK (sequence IN ('SLOT', 'CATEGORY', 'PROMPT'))
);

INSERT INTO prompt_ordering (sequence) VALUES ('SLOT'), ('CATEGORY'), ('PROMPT');

-- The slots a prompt can fill, in display order.
--
-- Slot positions are unique but deliberately *not* dense: a create appends behind
-- the last one, a delete leaves its position behind, and there is no reorder
-- route. The gaps are visible to nobody, because the display order is what the
-- position decides, not its value.
CREATE TABLE prompt_slots (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    position integer NOT NULL,
    CONSTRAINT pk_prompt_slots PRIMARY KEY (id),
    CONSTRAINT ck_prompt_slots_position_positive CHECK (position > 0),
    CONSTRAINT ux_prompt_slots_position UNIQUE (position)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE UNIQUE INDEX ux_prompt_slots_name_lower ON prompt_slots (LOWER(name));

-- The variants of a slot. A variant cannot change its slot, which is why the
-- update contract has no slot id, and a slot that still has variants cannot be
-- deleted.
CREATE TABLE prompt_slot_variants (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    slot_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    prompt text NOT NULL,
    description character varying(1000) NULL,
    llm character varying(255) NULL,
    CONSTRAINT pk_prompt_slot_variants PRIMARY KEY (id),
    CONSTRAINT fk_prompt_slot_variants_slot
        FOREIGN KEY (slot_id)
        REFERENCES prompt_slots (id)
        ON DELETE RESTRICT
);

CREATE INDEX ix_prompt_slot_variants_slot_id ON prompt_slot_variants (slot_id);

-- Globally unique across all slots, not per slot: the same variant name in two
-- slots would be the same variant twice.
CREATE UNIQUE INDEX ux_prompt_slot_variants_name_lower
    ON prompt_slot_variants (LOWER(name));

-- The prompt category structure. Category positions are global and dense;
-- subcategory positions are dense within their category.
CREATE TABLE prompt_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(200) NOT NULL,
    position integer NOT NULL,
    active boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_prompt_categories PRIMARY KEY (id),
    CONSTRAINT ck_prompt_categories_position_positive CHECK (position > 0),
    CONSTRAINT ux_prompt_categories_position UNIQUE (position)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE UNIQUE INDEX ux_prompt_categories_name_lower ON prompt_categories (LOWER(name));

CREATE TABLE prompt_subcategories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    category_id bigint NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(1000) NULL,
    position integer NOT NULL,
    active boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_prompt_subcategories PRIMARY KEY (id),
    CONSTRAINT ak_prompt_subcategories_id_category_id UNIQUE (id, category_id),
    CONSTRAINT fk_prompt_subcategories_category
        FOREIGN KEY (category_id)
        REFERENCES prompt_categories (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_prompt_subcategories_position_positive CHECK (position > 0),
    CONSTRAINT ux_prompt_subcategories_category_position UNIQUE (category_id, position)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE UNIQUE INDEX ux_prompt_subcategories_category_name_lower
    ON prompt_subcategories (category_id, LOWER(name));

-- The prompts themselves.
--
-- `category_id` is required, so a subcategory can never be the only reference a
-- prompt has -- no check constraint is needed to say so. The composite foreign
-- key is what makes "a prompt's subcategory belongs to the prompt's category" a
-- database fact instead of a preliminary read.
--
-- `price_id` is nullable because the pricing module owns price rows and a prompt
-- may exist without one; UNIQUE (price_id) is the backstop that keeps a price
-- from belonging to two prompts, which already holds by construction because no
-- prompt contract accepts a price id.
CREATE TABLE prompts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    position integer NOT NULL,
    title character varying(255) NOT NULL,
    prompt_text text NOT NULL,
    category_id bigint NOT NULL,
    subcategory_id bigint NULL,
    example_image_filename character varying(255) NULL,
    price_id bigint NULL,
    llm character varying(255) NULL,
    active boolean NOT NULL,
    archived boolean NOT NULL,
    CONSTRAINT pk_prompts PRIMARY KEY (id),
    CONSTRAINT ck_prompts_position_positive CHECK (position > 0),
    CONSTRAINT ux_prompts_position UNIQUE (position)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT fk_prompts_category
        FOREIGN KEY (category_id)
        REFERENCES prompt_categories (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_prompts_subcategory
        FOREIGN KEY (subcategory_id, category_id)
        REFERENCES prompt_subcategories (id, category_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_prompts_price
        FOREIGN KEY (price_id)
        REFERENCES prices (id)
        ON DELETE RESTRICT,
    CONSTRAINT ux_prompts_price_id UNIQUE (price_id)
);

CREATE INDEX ix_prompts_category_id ON prompts (category_id);
CREATE INDEX ix_prompts_subcategory_id ON prompts (subcategory_id, category_id);

-- Which slot variants a prompt is composed of. Deleting a prompt takes its
-- mappings with it; deleting a variant a prompt still uses is refused, which is
-- what the "still in use" answer of the variant delete route reports.
--
-- The key is only (prompt_id, slot_variant_id): more than one variant of the same
-- slot may be mapped to one prompt, and that is intentional.
CREATE TABLE prompt_slot_variant_mappings (
    prompt_id bigint NOT NULL,
    slot_variant_id bigint NOT NULL,
    CONSTRAINT pk_prompt_slot_variant_mappings PRIMARY KEY (prompt_id, slot_variant_id),
    CONSTRAINT fk_prompt_slot_variant_mappings_prompt
        FOREIGN KEY (prompt_id)
        REFERENCES prompts (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_prompt_slot_variant_mappings_slot_variant
        FOREIGN KEY (slot_variant_id)
        REFERENCES prompt_slot_variants (id)
        ON DELETE RESTRICT
);

CREATE INDEX ix_prompt_slot_variant_mappings_slot_variant_id
    ON prompt_slot_variant_mappings (slot_variant_id);
