-- The cart schema of the Cart migration (docs/migration/cart-migration.md).
--
-- Three ideas shape it:
--
-- 1. The guest session token is the identity of a cart. `user_id` is only ever
--    adopted onto an existing row (login) and reverts to NULL when the user is
--    deleted, so the data stays reachable through the token instead of
--    cascading into cart lines.
-- 2. Every invariant PostgreSQL can express lives here: one active cart per
--    guest token, a variant that really belongs to its article, quantities
--    between 1 and 99, and dense-enough line positions.
-- 3. Nothing that a cart line snapshots may be restricted by master data. A
--    prompt or a promotion may be deleted; the snapshot on the line survives.

-- The registry of uploaded print images. A row is written by the pre-upload
-- endpoint before any cart line references it, so an upload that is never added
-- to a cart simply stays orphaned (accepted, see the migration record).
--
-- The file itself lives in the image module's private storage under exactly the
-- name stored here: a lowercase UUID with dashes plus `.webp`, because every
-- accepted upload is normalized to WebP.
CREATE TABLE print_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    filename character varying(64) NOT NULL,
    guest_session_token text NULL,
    user_id bigint NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_print_images PRIMARY KEY (id),
    CONSTRAINT ux_print_images_filename UNIQUE (filename),
    CONSTRAINT ck_print_images_owner
        CHECK (guest_session_token IS NOT NULL OR user_id IS NOT NULL),
    CONSTRAINT fk_print_images_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_print_images_guest_session_token
    ON print_images (guest_session_token);
CREATE INDEX ix_print_images_user_id ON print_images (user_id);

-- The cart itself. `promotion_id` is deliberately ON DELETE SET NULL and not
-- RESTRICT: the promotion module maps SQL state 23503 of a promotion delete
-- wholesale to "this promotion has redemptions", so a second restricting
-- reference would corrupt that answer. A deleted promotion therefore simply
-- falls off the carts that held it.
CREATE TABLE carts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    guest_session_token text NOT NULL,
    user_id bigint NULL,
    status text NOT NULL,
    promotion_id bigint NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_carts PRIMARY KEY (id),
    CONSTRAINT ck_carts_status CHECK (status IN ('ACTIVE', 'CHECKED_OUT')),
    CONSTRAINT fk_carts_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_carts_promotion
        FOREIGN KEY (promotion_id)
        REFERENCES promotions (id)
        ON DELETE SET NULL
);

-- One active cart per guest token. The partial index is what makes the
-- find-or-create of two concurrent first mutations safe: the loser of the race
-- sees a unique violation instead of creating a second cart. Checked-out carts
-- are outside the index, so a token may accumulate any number of them.
CREATE UNIQUE INDEX ux_carts_active_guest_session_token
    ON carts (guest_session_token)
    WHERE status = 'ACTIVE';

CREATE INDEX ix_carts_user_id ON carts (user_id);

-- One line of a cart. `price_cents` and `prompt_price_cents` are snapshots taken
-- when the line was added, which is why the prompt reference may be set to NULL
-- without losing what the customer was quoted.
CREATE TABLE cart_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    cart_id bigint NOT NULL,
    article_id bigint NOT NULL,
    variant_id bigint NOT NULL,
    quantity integer NOT NULL,
    price_cents integer NOT NULL,
    prompt_id bigint NULL,
    prompt_price_cents integer NOT NULL DEFAULT 0,
    print_image_id bigint NULL,
    position integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_cart_items PRIMARY KEY (id),
    CONSTRAINT ck_cart_items_quantity CHECK (quantity BETWEEN 1 AND 99),
    CONSTRAINT ck_cart_items_price_cents_non_negative CHECK (price_cents >= 0),
    CONSTRAINT ck_cart_items_prompt_price_cents_non_negative
        CHECK (prompt_price_cents >= 0),
    CONSTRAINT ck_cart_items_position_positive CHECK (position > 0),
    CONSTRAINT ux_cart_items_cart_id_position UNIQUE (cart_id, position),
    CONSTRAINT fk_cart_items_cart
        FOREIGN KEY (cart_id)
        REFERENCES carts (id)
        ON DELETE CASCADE,
    -- The composite key is the whole point: a variant of another article cannot
    -- be stored on a line at all, so "does this variant belong to that article"
    -- is a database fact and never a preliminary read.
    CONSTRAINT fk_cart_items_variant
        FOREIGN KEY (variant_id, article_id)
        REFERENCES article_variant_identities (id, article_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_prompt
        FOREIGN KEY (prompt_id)
        REFERENCES prompts (id)
        ON DELETE SET NULL,
    -- RESTRICT, because a print image that a cart line still points at must not
    -- disappear under it.
    CONSTRAINT fk_cart_items_print_image
        FOREIGN KEY (print_image_id)
        REFERENCES print_images (id)
        ON DELETE RESTRICT
);

CREATE INDEX ix_cart_items_cart_id ON cart_items (cart_id);
CREATE INDEX ix_cart_items_print_image_id ON cart_items (print_image_id);
