-- The order schema of the Order migration (docs/migration/order-migration.md).
--
-- Three ideas shape it:
--
-- 1. An order is an immutable record of what was bought. Everything a later
--    reader needs — addresses, e-mail, names, prices, supplier article number,
--    the five print measurements — is snapshotted at placement, so changing or
--    deleting master data afterwards can never rewrite history. That is why
--    `article_id` and `variant_id` carry no catalog foreign key at all: an
--    order must survive the deletion of the article it was placed for. It is a
--    deliberate asymmetry to `cart_items`, whose lines are a live selection.
-- 2. Whatever the money says must add up in the database: every amount is
--    non-negative and `total = subtotal + shipping - discount`.
-- 3. Placing an order twice is a database-level impossibility. The partial
--    unique index over `cart_id` lets exactly one non-cancelled order exist per
--    cart, so two parallel checkout requests end as one stored order and one
--    23505 the repository reports as "already placed".
-- 4. Every order carries its own access token (issue #110). It is the durable
--    handle the confirmation mail links to, so a customer who never signs in
--    can still read the order they placed — long after a guest cookie expired.
--    It is `NOT NULL` for *all* orders, account orders included, and unique,
--    which is what makes the token alone a sufficient answer to "which order".

-- The order itself. `user_id` is ON DELETE SET NULL like every other customer
-- owned row: the record survives the account. `promotion_id` is RESTRICT and
-- not SET NULL, because the redemption below is what makes the discount on this
-- order auditable — a promotion that an order used cannot be deleted.
CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    cart_id bigint NOT NULL,
    guest_session_token text NULL,
    user_id bigint NULL,
    promotion_id bigint NULL,
    -- 256 bits of randomness, URL-safe Base64 without padding (43 characters).
    -- The application generates it per insert attempt; a collision is a 23505
    -- like any other and is retried with a fresh token.
    access_token text NOT NULL,
    status text NOT NULL,
    shipping_first_name character varying(100) NOT NULL,
    shipping_last_name character varying(100) NOT NULL,
    shipping_street character varying(200) NOT NULL,
    shipping_house_number character varying(20) NOT NULL,
    shipping_postal_code character varying(10) NOT NULL,
    shipping_city character varying(100) NOT NULL,
    shipping_country character varying(2) NOT NULL,
    billing_first_name character varying(100) NOT NULL,
    billing_last_name character varying(100) NOT NULL,
    billing_street character varying(200) NOT NULL,
    billing_house_number character varying(20) NOT NULL,
    billing_postal_code character varying(10) NOT NULL,
    billing_city character varying(100) NOT NULL,
    billing_country character varying(2) NOT NULL,
    email character varying(255) NOT NULL,
    phone text NULL,
    subtotal_cents integer NOT NULL,
    shipping_cost_cents integer NOT NULL,
    discount_cents integer NOT NULL,
    total_cents integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT ck_orders_status CHECK (status IN ('PENDING', 'PAID', 'CANCELLED')),
    -- An order always has someone to show it to: the guest who placed it, the
    -- account that owns it, or both.
    CONSTRAINT ck_orders_owner
        CHECK (guest_session_token IS NOT NULL OR user_id IS NOT NULL),
    CONSTRAINT ck_orders_subtotal_cents_non_negative CHECK (subtotal_cents >= 0),
    CONSTRAINT ck_orders_shipping_cost_cents_non_negative CHECK (shipping_cost_cents >= 0),
    CONSTRAINT ck_orders_discount_cents_non_negative CHECK (discount_cents >= 0),
    CONSTRAINT ck_orders_total_cents_non_negative CHECK (total_cents >= 0),
    -- The four amounts are stored, not derived, so this is the rule that keeps
    -- them one consistent statement about the same order.
    CONSTRAINT ck_orders_total_cents_consistent
        CHECK (total_cents = subtotal_cents + shipping_cost_cents - discount_cents),
    -- RESTRICT: the cart an order was placed from is the evidence of what was
    -- ordered and must not vanish under it.
    CONSTRAINT fk_orders_cart
        FOREIGN KEY (cart_id)
        REFERENCES carts (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_orders_promotion
        FOREIGN KEY (promotion_id)
        REFERENCES promotions (id)
        ON DELETE RESTRICT
);

-- One live order per cart. Cancelled orders fall out of the index, so a cart
-- whose payment failed can be checked out again; anything else is a duplicate
-- placement and fails with 23505 instead of charging twice.
CREATE UNIQUE INDEX ux_orders_live_cart
    ON orders (cart_id)
    WHERE status <> 'CANCELLED';

-- One order per access token. The index is what makes the token an identity
-- rather than a filter: the lookup route reads a single row by it, and a
-- generated token that already exists fails with 23505 instead of quietly
-- pointing two orders at one link.
CREATE UNIQUE INDEX ux_orders_access_token ON orders (access_token);

-- The order history of an account, newest first — exactly the list query.
CREATE INDEX ix_orders_user_id_created_at ON orders (user_id, created_at DESC);
CREATE INDEX ix_orders_guest_session_token ON orders (guest_session_token);

CREATE INDEX ix_orders_promotion_id ON orders (promotion_id);

-- One ordered line. Every column from `article_name` down is a snapshot: the
-- names the customer saw, the prices they were quoted, and the production data
-- the PDF is laid out from. Only `prompt_id` and `print_image_id` stay
-- references, because the reorder flow needs the live rows behind them.
CREATE TABLE order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id bigint NOT NULL,
    position integer NOT NULL,
    article_id bigint NOT NULL,
    variant_id bigint NOT NULL,
    article_name character varying(255) NOT NULL,
    variant_name character varying(255) NOT NULL,
    supplier_article_number character varying(255) NULL,
    print_template_width_mm integer NULL,
    print_template_height_mm integer NULL,
    document_format_width_mm integer NULL,
    document_format_height_mm integer NULL,
    document_format_margin_bottom_mm integer NULL,
    quantity integer NOT NULL,
    price_cents integer NOT NULL,
    prompt_price_cents integer NOT NULL DEFAULT 0,
    prompt_id bigint NULL,
    print_image_id bigint NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT ck_order_items_position_positive CHECK (position > 0),
    CONSTRAINT ux_order_items_order_id_position UNIQUE (order_id, position),
    CONSTRAINT ck_order_items_quantity CHECK (quantity BETWEEN 1 AND 99),
    CONSTRAINT ck_order_items_price_cents_non_negative CHECK (price_cents >= 0),
    CONSTRAINT ck_order_items_prompt_price_cents_non_negative
        CHECK (prompt_price_cents >= 0),
    -- A measurement is either unknown or a real length; zero and negative
    -- values would silently produce an unusable production page.
    CONSTRAINT ck_order_items_measurements_positive
        CHECK (
            (print_template_width_mm IS NULL OR print_template_width_mm > 0)
            AND (print_template_height_mm IS NULL OR print_template_height_mm > 0)
            AND (document_format_width_mm IS NULL OR document_format_width_mm > 0)
            AND (document_format_height_mm IS NULL OR document_format_height_mm > 0)
            AND (
                document_format_margin_bottom_mm IS NULL
                OR document_format_margin_bottom_mm > 0
            )
        ),
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_order_items_prompt
        FOREIGN KEY (prompt_id)
        REFERENCES prompts (id)
        ON DELETE SET NULL,
    -- RESTRICT, because the print image is what production actually prints.
    CONSTRAINT fk_order_items_print_image
        FOREIGN KEY (print_image_id)
        REFERENCES print_images (id)
        ON DELETE RESTRICT
);

CREATE INDEX ix_order_items_order_id ON order_items (order_id);
CREATE INDEX ix_order_items_print_image_id ON order_items (print_image_id);

-- The redemption column the Promotion migration deferred until orders existed
-- (see docs/migration/promotion-migration.md). It is NOT NULL and unique:
-- a redemption without the order it paid for does not exist in this schema, and
-- one order redeems a promotion at most once. RESTRICT keeps the redeemed order
-- alive for as long as its redemption is counted against a usage limit.
ALTER TABLE promotion_redemptions
    ADD COLUMN order_id bigint NOT NULL,
    ADD CONSTRAINT ux_promotion_redemptions_order UNIQUE (order_id),
    ADD CONSTRAINT fk_promotion_redemptions_order
        FOREIGN KEY (order_id)
        REFERENCES orders (id)
        ON DELETE RESTRICT;

-- The foreign key the Production migration deferred until orders existed
-- (see docs/migration/production-migration.md). RESTRICT, because an open
-- production request is a promise to actually produce that order.
ALTER TABLE production_requests
    ADD CONSTRAINT fk_production_requests_order
        FOREIGN KEY (order_id)
        REFERENCES orders (id)
        ON DELETE RESTRICT;
