-- The payment schema of the Payment migration (docs/migration/payment-migration.md).
--
-- A payment is one attempt at collecting the money for one order. The order is
-- the identity the whole module is keyed on: `order_id` is NOT NULL and its
-- foreign key is RESTRICT, because an order that somebody may have been charged
-- for must not vanish under its payment record.
--
-- Four legacy columns are gone and one changed its nullability. `currency` was
-- always 'EUR' (deviation D4); `description` was always "Order #<id>" and
-- `redirect_url` was derivable from the settings and the order id, and both were
-- write-only (D5). `checkout_url` went the other way and became NOT NULL (D6):
-- the repeated `start` of a double-clicked checkout answers the stored URL
-- instead of creating a second payment, so it is now actually read.
--
-- The status vocabulary is Mollie's, uppercased. Note `CANCELED` with one L,
-- next to the order module's `CANCELLED` with two: the two words belong to two
-- different systems and are deliberately not unified.
CREATE TABLE payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id bigint NOT NULL,
    mollie_payment_id character varying(64) NOT NULL,
    status text NOT NULL,
    amount_cents integer NOT NULL,
    checkout_url text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_payments PRIMARY KEY (id),
    CONSTRAINT ux_payments_mollie_payment_id UNIQUE (mollie_payment_id),
    CONSTRAINT ck_payments_status CHECK (
        status IN ('OPEN','PENDING','AUTHORIZED','PAID','FAILED','CANCELED','EXPIRED')
    ),
    CONSTRAINT ck_payments_amount_cents_positive CHECK (amount_cents > 0),
    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT
);

-- One live payment per order (the Wave-2 half of Order deviation D10). A
-- payment that failed, was cancelled, or expired falls out of the index, so a
-- Wave-3 retry may start a second payment for the same order; two live
-- payments for one order fail with 23505 instead of charging twice.
CREATE UNIQUE INDEX ux_payments_live_order
    ON payments (order_id)
    WHERE status NOT IN ('FAILED','CANCELED','EXPIRED');

-- The order-list join.
CREATE INDEX ix_payments_order_id ON payments (order_id);
