-- The promotion reservation of the Checkout migration
-- (docs/migration/checkout-migration.md, deviations D1 and D2).
--
-- A reservation is the in-flight half of a usage limit: between the moment a
-- checkout locks a promotion for a cart and the moment the payment either
-- redeems it or ends, the capacity is held here. Counted next to
-- `promotion_redemptions`, it is what keeps two customers from spending the
-- last unit of a `usage_limit_total = 1` promotion at the same time.
--
-- The cart is the identity, not the order: the reservation is taken before an
-- order exists (the checkout reserves first, then places), and the cart is the
-- one thing that spans the whole journey. `cart_id` is therefore UNIQUE — a
-- cart holds at most one reservation, so re-reserving the same cart updates its
-- row instead of counting a second time.
--
-- There is no `expires_at` (D2, Joe's decision of 2026-08-02): a reservation
-- ends only through `redeem`, through the cancellation of its order, or when a
-- payment ends terminally. The accepted consequence is that a crash between the
-- reservation and its order, or a permanently missed terminal webhook, blocks
-- that capacity until admin tooling removes the row.
--
-- The three foreign keys differ on purpose:
--   * `promotion_id` RESTRICT — a promotion somebody is currently checking out
--     with must not vanish underneath them; the promotion module reports the
--     existing "still in use" conflict;
--   * `cart_id` CASCADE — the reservation is nothing but a property of that
--     cart, so it dies with it;
--   * `user_id` SET NULL — the reservation still holds capacity after the
--     account behind it is deleted, exactly like a redemption does.
CREATE TABLE promotion_reservations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    promotion_id bigint NOT NULL,
    cart_id bigint NOT NULL,
    user_id bigint NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_promotion_reservations PRIMARY KEY (id),
    CONSTRAINT ux_promotion_reservations_cart UNIQUE (cart_id),
    CONSTRAINT fk_promotion_reservations_promotion
        FOREIGN KEY (promotion_id) REFERENCES promotions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_promotion_reservations_cart
        FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
    CONSTRAINT fk_promotion_reservations_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

-- The two counts every limit check runs: the total capacity in flight, and the
-- share of it that belongs to one customer.
CREATE INDEX ix_promotion_reservations_promotion_id
    ON promotion_reservations (promotion_id);
CREATE INDEX ix_promotion_reservations_promotion_id_user_id
    ON promotion_reservations (promotion_id, user_id);
