CREATE TABLE email_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    idempotency_hash bytea NOT NULL,
    intent_hash bytea NOT NULL,
    email_kind varchar(64) NOT NULL,
    source_id bigint NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'PENDING',
    retry_count integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_token uuid,
    lease_expires_at timestamptz,
    last_error_code varchar(64),
    last_error_message varchar(512),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamptz,
    CONSTRAINT pk_email_jobs PRIMARY KEY (id),
    CONSTRAINT uq_email_jobs_idempotency_hash UNIQUE (idempotency_hash),
    CONSTRAINT ck_email_jobs_idempotency_hash_length CHECK (octet_length(idempotency_hash) = 32),
    CONSTRAINT ck_email_jobs_intent_hash_length CHECK (octet_length(intent_hash) = 32),
    CONSTRAINT ck_email_jobs_kind CHECK (email_kind IN ('ORDER_CONFIRMATION', 'PRODUCER_PDF_NOTIFICATION')),
    CONSTRAINT ck_email_jobs_source_id_positive CHECK (source_id > 0),
    CONSTRAINT ck_email_jobs_status CHECK (status IN ('PENDING', 'PROCESSING', 'TRANSMITTED')),
    CONSTRAINT ck_email_jobs_retry_count_nonnegative CHECK (retry_count >= 0),
    CONSTRAINT ck_email_jobs_state CHECK (
        (status = 'PENDING' AND lease_token IS NULL AND lease_expires_at IS NULL AND completed_at IS NULL)
        OR (status = 'PROCESSING' AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL AND completed_at IS NULL)
        OR (status = 'TRANSMITTED' AND lease_token IS NULL AND lease_expires_at IS NULL
            AND completed_at IS NOT NULL AND last_error_code IS NULL AND last_error_message IS NULL)
    )
);

CREATE INDEX ix_email_jobs_claim ON email_jobs (status, next_attempt_at, id);
CREATE INDEX ix_email_jobs_lease_recovery ON email_jobs (lease_expires_at, id)
    WHERE status = 'PROCESSING';
CREATE INDEX ix_email_jobs_pending_retries ON email_jobs (retry_count DESC, next_attempt_at, id)
    WHERE status <> 'TRANSMITTED';
