CREATE TABLE email_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    email_kind varchar(64) NOT NULL,
    source_id bigint NOT NULL,
    attempt_count integer NOT NULL DEFAULT 0,
    last_error_code varchar(64),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at timestamptz,
    CONSTRAINT pk_email_jobs PRIMARY KEY (id),
    CONSTRAINT uq_email_jobs_reference UNIQUE (email_kind, source_id),
    CONSTRAINT ck_email_jobs_kind CHECK (email_kind IN ('ORDER_CONFIRMATION', 'PRODUCER_PDF_NOTIFICATION')),
    CONSTRAINT ck_email_jobs_source_id_positive CHECK (source_id > 0),
    CONSTRAINT ck_email_jobs_attempt_count_nonnegative CHECK (attempt_count >= 0)
);
