CREATE TABLE production_destinations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    supplier_id bigint NOT NULL,
    channel varchar(32) NOT NULL,
    label varchar(255) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    host varchar(255) NOT NULL,
    port integer NOT NULL DEFAULT 22,
    username varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    host_key_fingerprint varchar(255) NOT NULL,
    remote_path varchar(1024) NOT NULL DEFAULT '/',
    timeout_seconds integer NOT NULL,
    notification_email varchar(255),
    notification_name varchar(255),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_production_destinations PRIMARY KEY (id),
    CONSTRAINT fk_production_destinations_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE RESTRICT,
    CONSTRAINT ck_production_destinations_channel CHECK (channel IN ('SFTP')),
    CONSTRAINT ck_production_destinations_port_range CHECK (port BETWEEN 1 AND 65535),
    CONSTRAINT ck_production_destinations_timeout_range
        CHECK (timeout_seconds BETWEEN 1 AND 3600)
);

CREATE INDEX ix_production_destinations_supplier_id ON production_destinations (supplier_id);
