CREATE TABLE production_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id bigint NOT NULL,
    attempt_count integer NOT NULL DEFAULT 0,
    last_error_code varchar(64),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at timestamptz,
    CONSTRAINT pk_production_requests PRIMARY KEY (id),
    CONSTRAINT uq_production_requests_order UNIQUE (order_id),
    CONSTRAINT ck_production_requests_order_id_positive CHECK (order_id > 0),
    CONSTRAINT ck_production_requests_attempt_count_nonnegative CHECK (attempt_count >= 0)
);
