CREATE TABLE production_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    request_id bigint NOT NULL,
    supplier_id bigint NOT NULL,
    file_name varchar(255) NOT NULL,
    content_sha256 varchar(64),
    generation_attempt_count integer NOT NULL DEFAULT 0,
    last_generation_error_code varchar(64),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    generated_at timestamptz,
    CONSTRAINT pk_production_jobs PRIMARY KEY (id),
    CONSTRAINT uq_production_jobs_request_supplier UNIQUE (request_id, supplier_id),
    CONSTRAINT fk_production_jobs_request
        FOREIGN KEY (request_id) REFERENCES production_requests (id) ON DELETE RESTRICT,
    CONSTRAINT fk_production_jobs_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE RESTRICT,
    CONSTRAINT ck_production_jobs_generation_attempt_count_nonnegative
        CHECK (generation_attempt_count >= 0)
);

CREATE INDEX ix_production_jobs_supplier_id ON production_jobs (supplier_id);
