CREATE TABLE production_deliveries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    production_job_id bigint NOT NULL,
    destination_id bigint NOT NULL,
    attempt_count integer NOT NULL DEFAULT 0,
    last_error_code varchar(64),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_at timestamptz,
    CONSTRAINT pk_production_deliveries PRIMARY KEY (id),
    CONSTRAINT uq_production_deliveries_job_destination UNIQUE (production_job_id, destination_id),
    CONSTRAINT fk_production_deliveries_job
        FOREIGN KEY (production_job_id) REFERENCES production_jobs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_production_deliveries_destination
        FOREIGN KEY (destination_id) REFERENCES production_destinations (id) ON DELETE RESTRICT,
    CONSTRAINT ck_production_deliveries_attempt_count_nonnegative CHECK (attempt_count >= 0)
);

CREATE INDEX ix_production_deliveries_destination_id ON production_deliveries (destination_id);
