ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }

  application {
    modules = [ shop.voenix.ApplicationKt.module ]
  }
}

database {
  jdbcUrl = "jdbc:postgresql://localhost:5432/voenix_kotlin"
  jdbcUrl = ${?DATABASE_JDBC_URL}

  username = "voenix"
  username = ${?DATABASE_USERNAME}

  password = "voenix"
  password = ${?DATABASE_PASSWORD}

  maximumPoolSize = 5
  maximumPoolSize = ${?DATABASE_MAX_POOL_SIZE}
}
