ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }

  application {
    modules = [ shop.voenix.ApplicationKt.module ]
  }
}

Database {
  Host = "localhost"
  Host = ${?DATABASE_HOST}

  Port = 5432
  Port = ${?DATABASE_PORT}

  Database = "voenix"
  Database = ${?DATABASE_NAME}

  Username = ""
  Username = ${?DATABASE_USERNAME}

  Password = ""
  Password = ${?DATABASE_PASSWORD}

  SearchPath = "voenix"
  SearchPath = ${?DATABASE_SEARCH_PATH}

  SslMode = "Disable"
  SslMode = ${?DATABASE_SSL_MODE}

  MaximumPoolSize = 100
  MaximumPoolSize = ${?DATABASE_MAX_POOL_SIZE}
}

Auth {
  SessionSecret = ""
  SessionSecret = ${?AUTH_SESSION_SECRET}
}
