CREATE TABLE countries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    country_code character varying(2) NOT NULL,
    CONSTRAINT "PK_countries" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX uk_countries_country_code
    ON countries (country_code);

CREATE UNIQUE INDEX ix_countries_name_lower
    ON countries (LOWER(name));

INSERT INTO countries (name, country_code)
VALUES
    ('Germany', 'DE'),
    ('France', 'FR'),
    ('Italy', 'IT'),
    ('Austria', 'AT'),
    ('Belgium', 'BE'),
    ('Netherlands', 'NL'),
    ('Spain', 'ES'),
    ('Sweden', 'SE')
ON CONFLICT (country_code) DO NOTHING;
