CREATE TABLE value_added_taxes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    percent integer NOT NULL,
    description text NULL,
    is_default boolean NOT NULL,
    CONSTRAINT pk_value_added_taxes PRIMARY KEY (id),
    CONSTRAINT ck_value_added_taxes_percent_range CHECK (percent >= 0 AND percent <= 100)
);

CREATE UNIQUE INDEX ux_value_added_taxes_name
    ON value_added_taxes (name);

CREATE UNIQUE INDEX ux_value_added_taxes_single_default
    ON value_added_taxes (is_default)
    WHERE is_default;
