CREATE TABLE suppliers (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    title character varying(255) NULL,
    first_name character varying(255) NULL,
    last_name character varying(255) NULL,
    street character varying(255) NULL,
    house_number character varying(255) NULL,
    city character varying(255) NULL,
    postal_code character varying(20) NULL,
    country_id bigint NULL,
    phone_number1 character varying(255) NULL,
    phone_number2 character varying(255) NULL,
    phone_number3 character varying(255) NULL,
    email character varying(255) NULL,
    website character varying(255) NULL,
    CONSTRAINT pk_suppliers PRIMARY KEY (id),
    CONSTRAINT fk_suppliers_country
        FOREIGN KEY (country_id) REFERENCES countries (id) ON DELETE SET NULL
);

CREATE INDEX ix_suppliers_country_id ON suppliers (country_id);
CREATE INDEX ix_suppliers_name_id ON suppliers (name, id);
