CREATE TABLE prices (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    purchase_vat_id bigint NOT NULL,
    purchase_calculation_mode text NOT NULL,
    purchase_active_row text NOT NULL,
    purchase_price_input_cents integer NOT NULL,
    purchase_cost_input_cents integer NOT NULL,
    purchase_cost_percent numeric(6, 2) NOT NULL,
    sales_vat_id bigint NOT NULL,
    sales_calculation_mode text NOT NULL,
    sales_active_row text NOT NULL,
    sales_margin_input_cents integer NOT NULL,
    sales_margin_percent numeric(6, 2) NOT NULL,
    sales_total_input_cents integer NOT NULL,
    CONSTRAINT pk_prices PRIMARY KEY (id),
    CONSTRAINT fk_prices_purchase_vat
        FOREIGN KEY (purchase_vat_id)
        REFERENCES value_added_taxes (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_prices_sales_vat
        FOREIGN KEY (sales_vat_id)
        REFERENCES value_added_taxes (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_prices_purchase_calculation_mode
        CHECK (purchase_calculation_mode IN ('NET', 'GROSS')),
    CONSTRAINT ck_prices_purchase_active_row
        CHECK (purchase_active_row IN ('COST', 'COST_PERCENT')),
    CONSTRAINT ck_prices_sales_calculation_mode
        CHECK (sales_calculation_mode IN ('NET', 'GROSS')),
    CONSTRAINT ck_prices_sales_active_row
        CHECK (sales_active_row IN ('MARGIN', 'MARGIN_PERCENT', 'TOTAL')),
    CONSTRAINT ck_prices_purchase_price_input_non_negative
        CHECK (purchase_price_input_cents >= 0),
    CONSTRAINT ck_prices_purchase_cost_input_non_negative
        CHECK (purchase_cost_input_cents >= 0),
    CONSTRAINT ck_prices_purchase_cost_percent_non_negative
        CHECK (purchase_cost_percent >= 0),
    CONSTRAINT ck_prices_sales_total_input_non_negative
        CHECK (sales_total_input_cents >= 0)
);

CREATE INDEX ix_prices_purchase_vat_id ON prices (purchase_vat_id);
CREATE INDEX ix_prices_sales_vat_id ON prices (sales_vat_id);
